//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public Nullable<int> RentaCarId { get; set; }
        public string Name { get; set; }
        public Nullable<long> Rate { get; set; }
        public Nullable<int> RatedBy { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<bool> Reserved { get; set; }
        public string Brand { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Seats { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
