//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public int RentaCarId { get; set; }
        public string Name { get; set; }
        public double Rate { get; set; }
        public int RatedBy { get; set; }
        public double Price { get; set; }
        public bool Reserved { get; set; }
        public string Brand { get; set; }
        public int Type { get; set; }
        public int Seats { get; set; }
        public int Year { get; set; }
    }
}
