//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarReservation
    {
        public int Id { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string CarName { get; set; }
        public Nullable<long> Price { get; set; }
    }
}
