//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int Id { get; set; }
        public System.DateTime DatumPoletanja { get; set; }
        public System.DateTime DatumSletanja { get; set; }
        public string VremeTrajanjaLeta { get; set; }
        public long DuzinaPutovanja { get; set; }
        public int BrojPresedanja { get; set; }
        public long Cena { get; set; }
        public string MestoPoletanja { get; set; }
        public string MestoSletanja { get; set; }
        public int OcenaLeta { get; set; }
        public int IdAvioKompanije { get; set; }
    }
}
