//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DatumPoletanja { get; set; }
        public Nullable<System.DateTime> DatumSletanja { get; set; }
        public string VremeTrajanjaLeta { get; set; }
        public Nullable<int> DuzinaPutovanja { get; set; }
        public Nullable<int> BrojPresedanja { get; set; }
        public Nullable<long> CenaBiznisKlase { get; set; }
        public Nullable<long> CenaEkonomskeKlase { get; set; }
        public Nullable<long> CenaPrveKlase { get; set; }
        public string MestoPoletanja { get; set; }
        public string MestoSletanja { get; set; }
        public Nullable<int> OcenaLeta { get; set; }
        public int IdAvioKompanije { get; set; }
        public Nullable<int> BrojSedista { get; set; }
    }
}
