//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AngularEntities3 : DbContext
    {
        public AngularEntities3()
            : base("name=AngularEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AirlineDetail> AirlineDetails { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Flight> Flights { get; set; }
        public virtual DbSet<FlightReservation> FlightReservations { get; set; }
        public virtual DbSet<Karta> Kartas { get; set; }
        public virtual DbSet<Presedanje> Presedanjes { get; set; }
        public virtual DbSet<RentaCar> RentaCars { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<Usermaster> Usermasters { get; set; }
        public virtual DbSet<UserActivation> UserActivations { get; set; }
    
        public virtual ObjectResult<Usp_Login_Result> Usp_Login(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Login_Result>("Usp_Login", userNameParameter, passwordParameter);
        }
    }
}
