//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usermaster
    {
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string PasswordConfirm { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string LastName { get; set; }
        public Nullable<int> IsApporved { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> TotalCnt { get; set; }
    }
}
